import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import {
  type WalletClient,
  usePublicClient,
  useWalletClient,
  useAccount,
} from "wagmi";
import { Provider } from "zksync-web3";
import React, { useEffect, useState } from "react";
import { ethers, providers } from "ethers";
import { useGoogleLogin } from "@react-oauth/google";
import TestAccount from "../abi/TestAccount.json";

const Home: NextPage = () => {
  const ETH_ADDRESS = "0x000000000000000000000000000000000000800A";
  const [account, setAccount] = useState<string>("");
  const [socialId, setSocialId] = useState<string>("");
  const [socialType, setSocialType] = useState<string>("");
  const { data } = useWalletClient();
  const publicClient = usePublicClient();
  const { isConnected } = useAccount();
  const signer = useEthersSigner({
    chainId: publicClient.chain.id,
  });
  const setLimit = async () => {
    const transaction = await axios.post(`/api/limit`, {
      socialId: socialId,
      socialType: socialType,
    });
  };

  const googleLogin = useGoogleLogin({
    onSuccess: async (tokenResponse) => {
      console.log(tokenResponse);
      // fetching userinfo can be done on the client or the server
      const userInfo = await axios.get(
        "https://www.googleapis.com/oauth2/v3/userinfo",
        {
          headers: { Authorization: `Bearer ${tokenResponse.access_token}` },
        }
      );
      const aa = await axios.post("/api/aa", {
        socialId: userInfo.data.sub,
        socialType: "1",
      });
      if (aa.data) {
        setAccount(aa.data.data.account);
        setSocialId(aa.data.data.socialId);
        setSocialType(aa.data.data.socialType);
      }
    },
  });

  const sendEthFromEoa = async () => {
    const accountContract = new ethers.Contract(
      account,
      TestAccount.abi,
      signer
    );
    console.log("address: ", data?.account.address);
    const estimateGas = await accountContract.estimateGas.testTransferFromEOA(
      data?.account.address,
      ethers.utils.parseEther("1")
    );
    console.log("estimateGas: ", estimateGas.toString());

    await (
      await accountContract.testTransferFromEOA(
        data?.account.address,
        ethers.utils.parseEther("1"),
        {
          gasPrice: await publicClient.getGasPrice(),
          gasLimit: estimateGas,
        }
      )
    ).wait();
  };
  useEffect(() => {
    console.log("isConnected: ", isConnected);
    if (isConnected && data?.account.address) {
      axios
        .post(`/api/aa-eoa`, {
          address: data?.account.address,
        })
        .then(async (response) => {
          setAccount(response.data.data.account);
          const accountContract = new ethers.Contract(
            response.data.data.account,
            TestAccount.abi,
            signer
          );
          await (await accountContract.approveToken()).wait();
        });
    }
  }, [isConnected, data]);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <button onClick={setLimit}>Set Limit</button>
        <button
          onClick={() => {
            googleLogin();
          }}
        >
          Login via google
        </button>
        <span className="">{account}</span>
        <button
          onClick={async () => {
            await axios.post(`/api/send-eth`, {
              socialId: socialId,
              socialType: socialType,
            });
          }}
        >
          Send 1 ETH
        </button>
        <button onClick={sendEthFromEoa}>Send 1 ETH from EOA</button>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export function walletClientToSigner(walletClient: WalletClient) {
  // const { account, chain } = walletClient;
  // const provider = new Provider(chain.rpcUrls.default.http[0]);
  const { account, chain, transport } = walletClient;
  const network = {
    chainId: chain.id,
    name: chain.name,
    ensAddress: chain.contracts?.ensRegistry?.address,
  };
  const provider = new providers.Web3Provider(transport, network);
  const signer = provider.getSigner(account.address);
  return signer;
}

/** Hook to convert a viem Wallet Client to an ethers.js Signer. */
export function useEthersSigner({ chainId }: { chainId?: number } = {}) {
  const { data: walletClient } = useWalletClient({ chainId });
  return React.useMemo(
    () => (walletClient ? walletClientToSigner(walletClient) : undefined),
    [walletClient]
  );
}

export default Home;
